development:
  adapter: mongodb
  database: devise_template-dev
  host: localhost

test:
  adapter: mongodb
  database: devise_template-test
  host: localhost

production:
  adapter: mongodb
  database: devise_template-prod
  host: localhost
