development:
  adapter: mongodb
  database: devise_template-dev
  host: localhost

development:
  adapter: mongodb
  database: devise_template-test
  host: localhost

development:
  adapter: mongodb
  database: devise_template-prod
  host: localhost
